AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Extract Predict Part 1 - File Server resource deployment
        Parameters:
          - KeyName
          - VPC
          - Subnet
          - SecurityGroupIds
          - LatestLinuxAmiId
Parameters:
  KeyName:
    Description: Select the key pair used to decrypt the Windows instance password
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  VPC:
    Description: Select the VPC for the Windows instance
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: Select the public subnet for the Windows instance
    Type: 'AWS::EC2::Subnet::Id'
  SecurityGroupIds:
    Description: Select one or more security groups for the Windows instance
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  LatestWindowsAmiId:
    Description: The latest Windows AMI ID for the Windows instance
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
    
Resources:
  WindowsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WindowsInstanceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      DeletionPolicy: Delete
  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref WindowsInstanceRole
  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "Windows-client-${AWS::StackName}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - "s3:Get*"
              - "s3:List*"
            Resource: "*"
      Roles:
        - !Ref WindowsInstanceRole
      DeletionPolicy: Delete
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
      
Outputs:
  WindowsInstance:
    Description: Private IP address of Windows instance
    Value: !GetAtt
      - WindowsInstance
      - PrivateIp
